
:::{.content-hidden when-format="html" when-page="index"}
# Quality Control for Python Applications
:::

**Description:**

Improve the maintainability and quality of your code. Attendees will become familiar with code modularity and organization principles, as well as quality control methods such as automated testing and continuous integration.

**Required Software:**

+ GitHub Desktop (requires a GitHub account)
+ VS Code Text Editor
+ Anaconda
+ Command Line Application (Terminal on Mac, Git Bash on Windows)

Attendees should be familiar with [Python Development Tools](https://s2t2.github.io/python-dev-tools-workshop-2024/) and [Version Control](https://s2t2.github.io/version-control-workshop-2024/) before attempting this workshop.

## Part 1: Refactoring Python Applications

**Learning Objectives:**

1. Translate code from a Python notebook into a local development repository.
2. Identify areas in code that can be simplified for improved readability and maintainability.
3. Refactor code by simplifying complex logic and removing duplication.
4. Discuss code organization concepts such as the single responsibility principle, and the DRY principle.
5. Organize code into modules to enhance scalability and maintainability, and practice importing code across multiple files.
6. Use automated tools such as Code Climate to perform automated assessments of code complexity and maintainability.

## Part 2: Testing Python Applications

**Learning Objectives:**

1. Discuss the benefits of implementing automated tests in a software development project.
2. Write automated tests for Python applications.
3. Execute automated tests locally using the `pytest` package.
4. Execute automated tests on a Continuous Integration server, using a GitHub Actions workflow.


<!--
## Agenda

Workshop Content:

+ 0:00 - Welcome and Announcements
+ 0:05 - Organizing Python Code:
  + [Refactoring](./notes/refactoring.qmd)
  + [Modules and Imports](./notes/modules-imports.qmd)
+ 0:30 - ["Codebase Cleanup" Exercise](./exercises/codebase-cleanup/exercise.qmd):
  + Practice refactoring and re-organizing Python code.
+ 0:60 - Stop

Extra Content:

+ Python Code Syntax and Style:
  + [Style Guidelines](./notes/style-guidelines.qmd)
  + [Documentation](./notes/documentation.qmd)
+ Object Oriented Programming:
  + [Object Oriented Programming](./notes/object-oriented-programming.qmd)
  + [Custom Classes](./notes/custom-classes.qmd)
+ ["Notebook Translation" Exercise](./exercises/notebook-translation/exercise.qmd):
  + Translate code from Python notebooks into a local development application.

-->
